// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class InserirTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void inserir() {
    driver.get("http://srbarriga.herokuapp.com/logout");
    driver.findElement(By.id("email")).sendKeys("barbara@testes");
    driver.findElement(By.id("senha")).sendKeys("123456");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Contas")).click();
    driver.findElement(By.linkText("Adicionar")).click();
    driver.findElement(By.id("nome")).sendKeys("Conta 01");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Conta adicionada com sucesso!"));
  }
  @Test
  public void alterar() {
    driver.get("http://srbarriga.herokuapp.com/");
    driver.findElement(By.linkText("Contas")).click();
    driver.findElement(By.linkText("Listar")).click();
    driver.findElement(By.cssSelector(".glyphicon-edit")).click();
    driver.findElement(By.id("nome")).sendKeys("Conta");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Conta alterada com sucesso!"));
  }
  @Test
  public void incluirContaExistente() {
    driver.get("http://srbarriga.herokuapp.com/");
    driver.findElement(By.linkText("Contas")).click();
    driver.findElement(By.linkText("Adicionar")).click();
    driver.findElement(By.id("nome")).sendKeys("Conta");
    driver.findElement(By.cssSelector(".btn")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Já existe uma conta com esse nome!"));
  }
  @Test
  public void excluirContaFinal() {
    driver.get("http://srbarriga.herokuapp.com/");
    driver.findElement(By.linkText("Contas")).click();
    driver.findElement(By.linkText("Listar")).click();
    driver.findElement(By.cssSelector(".glyphicon-remove-circle")).click();
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Conta removida com sucesso!"));
  }
}